name: CPP Azure Application Gateway
trigger:
  batch: true
  branches:
    include:
      - master

parameters:
  - name: components
    displayName: Component to Run
    type: object
    default:
      - deployment: "backendappgateway"
        environment: "dev"
        dependsOn: "Precheck"

  - name: location
    displayName: Location
    type: string
    default: "UK South"
    values:
      - "UK South"
      - "UK West"

variables:
  - name: tfversion
    value: 1.2.3
  - name: project
    value: application
  - name: timeoutInMinutes
    value: "60"
  - name: agentPool
    value: "ubuntu-18.04"
  - name: build
    value: $(Build.BuildNumber)
  - name: isMaster
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: product
    value: "cpp-platform"
  - name: tfInitSub
    value: ""

stages:
  - stage: precommit
    jobs:
    - job: pre
      pool:
        vmImage: ${{ variables.agentPool }}
      steps:
      - task: CmdLine@2
        displayName: 'Install pre commit'
        inputs:
          targetType: 'inline'
          script: |
            curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
            apt install pre-commit
            pre-commit install
            pre-commit run --all-files

  - stage: Precheck
    jobs:
      - job: Validate
        timeoutInMinutes: ${{ variables.timeoutInMinutes }}
        pool:
          vmImage: ${{ variables.agentPool }}
        steps:
          - task: TerraformInstaller@0
            displayName: Terraform install
            inputs:
              terraformVersion: ${{ variables.tfversion }}
